version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: mysqldbuser
        MYSQL_PASSWORD: password00
      ports:
        - 3306:3306
  keycloak:
      image: jboss/keycloak:12.0.4
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_PORT: 3306
        DB_USER: mysqldbuser
        DB_PASSWORD: password00
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin@123
        KEYCLOAK_LOGLEVEL: INFO
        JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - mysql